import { Inter, Urbanist, Raleway, DM_Sans } from 'next/font/google'
import './globals.css'

import localFont from 'next/font/local'

export const recoleta = localFont({ src: '../../public/fonts/recoleta.ttf' })

const inter = Inter({ subsets: ['latin'] })
const urban = Urbanist({ subsets: ['latin'] })
const dm = DM_Sans({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Travel Run',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Travel Run</title>
        <meta name='description' content='Description' />
      </head>
      <body className={dm.className}>{children}</body>
    </html>
  )
}
